apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebApi-deployment
spec:
  selector:
    matchLabels:
      app: webapi
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: webapi
        version: v1
    spec:
      containers:
      - name: webapi-container
        image: dockerwebapiet
        ports:
        - containerPort: 80